project_id = "lvvzcjyapspbplisneze"

[functions.send-email]
verify_jwt = false

[functions.get-partner-price]
verify_jwt = true

[functions.get-document]
verify_jwt = true

[functions.get-otc-quote]
verify_jwt = false

[functions.track-email-open]
verify_jwt = false

[functions.get-user-email]
verify_jwt = true

[functions.okx-operations]
verify_jwt = true
