project_id = "lvvzcjyapspbplisneze"

[functions.send-email]
verify_jwt = false

[functions.get-partner-price]
verify_jwt = true

[functions.get-document]
verify_jwt = true

[functions.get-otc-quote]
verify_jwt = false